[build]
  publish = "."
  command = "npm run sync"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.mp4"
  [headers.values]
    Content-Type = "video/mp4"

[[headers]]
  for = "*.mov"
  [headers.values]
    Content-Type = "video/quicktime"

[[headers]]
  for = "*.webm"
  [headers.values]
    Content-Type = "video/webm"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Enable pretty URLs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin" 