# Last deploy trigger: 2024-12-19 21:35:00
[build]
  command = "npm install && npm run sync"
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[headers]]
  for = "/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "*.mp4"
  [headers.values]
    Content-Type = "video/mp4"

[[headers]]
  for = "*.mov"
  [headers.values]
    Content-Type = "video/quicktime"

[[headers]]
  for = "*.webm"
  [headers.values]
    Content-Type = "video/webm"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Enable SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin" 